name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  http: ^1.3.0
  flutter_svg: ^2.0.9
  envied: ^1.1.1
  mockito: ^5.4.5
  skeletonizer: ^1.4.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo-ExtraBold.ttf
          weight: 800
  assets:
    - assets/icons/